services:
  qbitmf:
    build: images/qbitmf
    container_name: qbitmf
    privileged: true
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./interfaces:/interfaces:ro
      - ./config:/config
      - ./downloads:/downloads
    restart: unless-stopped
